Repository CS2103-AY1819S1-T13-2/main, pull requests merged in 2018-11, with the labels that each got.

#75 Profanity Filter for Feedback Command
  docs/UserGuide.adoc
  docs/words to ban/Bad_Words_List.txt
  src/main/java/seedu/address/logic/parser/FeedbackCommandParser.java
  src/main/java/seedu/address/logic/parser/RateCommandParser.java
  src/main/java/seedu/address/model/person/Feedback.java
  src/test/java/seedu/address/logic/parser/FeedbackCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RateCommandParserTest.java
  src/test/java/seedu/address/model/person/FeedbackTest.java
  src/test/java/systemtests/FeedbackCommandSystemTest.java
  src/test/java/systemtests/RateCommandSystemTest.java
Labels: type.Enhancement, v1.3

#103 Update Phone validation regex
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: type.Bug

#104 Fix ui bug
  src/main/java/seedu/address/commons/events/ui/HideStaffPanelEvent.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FeedbackCommand.java
  src/main/java/seedu/address/logic/commands/PrivacyCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/person/Manager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/model/person/ManagerTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: type.Bug

#81 add sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/UnfavouriteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement, v1.4

#108 Fix ui bug
  docs/images/Ui.png
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Feedback.java
  src/main/java/seedu/address/model/person/Manager.java
  src/main/resources/view/StaffPanel.fxml
  src/test/java/seedu/address/model/person/AddressTest.java
Labels: severity.High

#109 Update documentation for Feedback command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/FeedbackSequenceDiagram.pptx
  docs/images/FeedbackSequenceDiagram.png
  src/main/java/seedu/address/model/UserPrefs.java
Labels: priority.High
