Repository CS2103-AY1819S1-T13-2/main, pull requests merged in 2018-10, with the labels that each got.

#5 Update README.adoc
  README.adoc
  docs/images/Ui.png
Labels: v1.1

#13 UserGuide.adoc: Update
  docs/UserGuide.adoc
Labels: v1.1

#12 DeveloperGuide.adoc: Updated
  docs/DeveloperGuide.adoc
Labels: v1.1

#7 Implement RateCommand v1.1
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RateCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Rating.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RateCommandParserTest.java
  src/test/java/seedu/address/model/person/RatingTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: v1.1

#23 V1.1/V1.2 Daniel (Resolved merge conflicts)
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Department.java
  src/main/java/seedu/address/model/person/Manager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/DepartmentTest.java
  src/test/java/seedu/address/model/person/ManagerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: V1.2, enhancement, v1.1

#29 Update DeveloperGuide.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/RateSequenceDiagram.pptx
  docs/images/RateSequenceDiagram.png
Labels: type.Task, v1.2

#32 Devdoc ash
  docs/DeveloperGuide.adoc
  docs/diagrams/PrivacyCommandActivityDiagram.pptx
  docs/images/PrivacyCommandActivityDiagram.png
Labels: type.Task, v1.2

#31 README.adoc: Update badges for appVeyor and codacy
  README.adoc
Labels: type.Task

#27 Resolve merge conflicts for Privacy
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: priority.High, type.Enhancement, v1.1

#36 README.adoc: Update with the correct appVeyor link
  README.adoc
Labels: type.Task

#41 Redid Salary for (V1.1) and added OtHour, OtRate and PayDeductibles (V1.2)
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/FirstImplementation.png
  docs/images/SecondImplementation.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/OtHour.java
  src/main/java/seedu/address/model/person/OtRate.java
  src/main/java/seedu/address/model/person/PayDeductibles.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Salary.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/OtHourTest.java
  src/test/java/seedu/address/model/person/OtRateTest.java
  src/test/java/seedu/address/model/person/PayDeductiblesTest.java
  src/test/java/seedu/address/model/person/SalaryTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.High, type.Enhancement, v1.1, v1.2

#42 Minor app look changes and project tidy up
  copyright.txt
  docs/images/damithc.jpg
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/ssenisub.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Task

#47 v1.2 Feedback command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FeedbackCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FeedbackCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RateCommandParser.java
  src/main/java/seedu/address/model/person/Feedback.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FeedbackCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FeedbackCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/FeedbackTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.High, v1.2

#44 Update UI
  docs/images/SSENISUB.png
  docs/images/Ui.png
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/StaffPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/StaffPanel.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/guitests/guihandles/StaffPanelHandle.java
  src/test/java/seedu/address/ui/StaffPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: type.Task, v1.3

#50 Update UI & Test with feedback label
  docs/images/Ui.png
  src/main/java/seedu/address/ui/StaffPanel.java
  src/test/java/guitests/guihandles/StaffPanelHandle.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.Task

#53 Edit StaffPanel To Reflect Net Salary [v1.3]
  src/main/java/seedu/address/ui/StaffPanel.java
  src/main/resources/view/StaffPanel.fxml
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: v1.3

#54 add favourite command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/FeedbackCommand.java
  src/main/java/seedu/address/logic/commands/PrivacyCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FavouriteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FavouriteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FavouriteCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Enhancement, v1.3

#58 Fix bug for Rating and Feedback Commands
  src/main/java/seedu/address/logic/parser/FeedbackCommandParser.java
  src/main/java/seedu/address/logic/parser/RateCommandParser.java
  src/test/java/seedu/address/logic/parser/FeedbackCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RateCommandParserTest.java
  src/test/java/systemtests/FeedbackCommandSystemTest.java
  src/test/java/systemtests/RateCommandSystemTest.java
Labels: type.Bug

#62 update userdoc for privacy command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Task, v1.3

#64 user guide: add favourite command, remove lock-unlock command
  docs/UserGuide.adoc
Labels: v1.3

#67 update user guide and dev guide to include unfavourite command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: v1.3
